import type { CalendarService } from "./CalendarService";
import type { ContractService } from "./ContractService";
import type { DailySimulationService } from "./DailySimulationService";
import type { FinanceService } from "./FinanceService";
import type { FinancialHealthChecker } from "./finance/FinancialHealthChecker";
import type { FinancialPenaltyService } from "./finance/FinancialPenaltyService";
import type { InfrastructureService } from "./InfrastructureService";
import type { MarketingService } from "./MarketingService";
import type { MatchService } from "./MatchService";
import type { PlayerService } from "./PlayerService";
import type { ScoutingService } from "./ScoutingService";
import type { SeasonService } from "./SeasonService";
import type { SeasonTransitionManager } from "./season/SeasonTransitionManager";
import type { StaffService } from "./StaffService";
import type { StatsService } from "./StatsService";
import type { CupProgressionManager } from "./match/CupProgressionManager";
import type { MatchResultProcessor } from "./match/MatchResultProcessor";
import type { IUnitOfWork } from "../repositories/IUnitOfWork";
import type { TransferWindowManager } from "./transfer/TransferWindowManager";
import type { TransferService } from "./transfer/TransferService";
import type { SquadAnalysisService } from "./ai/SquadAnalysisService";
import type { AITransferDecisionMaker } from "./ai/AITransferDecisionMaker";
import type { DailyTransferProcessor } from "./ai/DailyTransferProcessor";
import type { NarrativeService } from "./narrative/NarrativeService";
import type { CPUSimulationService } from "./ai/CPUSimulationService";
import type { PlayerDevelopmentService } from "./PlayerDevelopmentService";
import type { ValuationService } from "./finance/ValuationService";
import type { OperationalCostsService } from "./finance/OperationalCostsService";
import type { RevenueService } from "./finance/RevenueService";
import type { YouthAcademyService } from "./YouthAcademyService";
import type { CompetitiveAnalysisService } from "./CompetitiveAnalysisService";
import type { InfrastructureHistoryService } from "./InfrastructureHistoryService";

export interface IServiceContainer {
  unitOfWork: IUnitOfWork;
  calendar: CalendarService;
  contract: ContractService;
  dailySimulation: DailySimulationService;
  finance: FinanceService;
  financialHealth: FinancialHealthChecker;
  financialPenalty: FinancialPenaltyService;
  infrastructure: InfrastructureService;
  marketing: MarketingService;
  match: MatchService;
  cupProgression: CupProgressionManager;
  matchResult: MatchResultProcessor;
  player: PlayerService;
  scouting: ScoutingService;
  season: SeasonService;
  seasonTransition: SeasonTransitionManager;
  staff: StaffService;
  stats: StatsService;
  transferWindow: TransferWindowManager;
  transfer: TransferService;
  squadAnalysis: SquadAnalysisService;
  aiTransferDecisionMaker: AITransferDecisionMaker;
  dailyTransferProcessor: DailyTransferProcessor;
  narrativeService: NarrativeService;
  cpuSimulation: CPUSimulationService;
  playerDevelopment: PlayerDevelopmentService;
  valuationService: ValuationService;
  operationalCosts: OperationalCostsService;
  revenueService: RevenueService;
  youthAcademy: YouthAcademyService;
  competitiveAnalysis: CompetitiveAnalysisService;
  infrastructureHistory: InfrastructureHistoryService;
}