import type { CalendarService } from "./CalendarService";
import type { ContractService } from "./ContractService";
import type { DailySimulationService } from "./DailySimulationService";
import type { FinanceService } from "./FinanceService";
import type { FinancialHealthChecker } from "./finance/FinancialHealthChecker";
import type { FinancialPenaltyService } from "./finance/FinancialPenaltyService";
import type { WageCalculator } from "./finance/WageCalculator";
import type { InfrastructureService } from "./InfrastructureService";
import type { MarketingService } from "./MarketingService";
import type { MatchService } from "./MatchService";
import type { PlayerService } from "./PlayerService";
import type { ScoutingService } from "./ScoutingService";
import type { SeasonService } from "./SeasonService";
import type { StaffService } from "./StaffService";
import type { StatsService } from "./StatsService";
import type { CupProgressionManager } from "./match/CupProgressionManager";
import type { MatchFanSatisfactionProcessor } from "./match/MatchFanSatisfactionProcessor";
import type { MatchFinancialsProcessor } from "./match/MatchFinancialsProcessor";
import type { MatchResultProcessor } from "./match/MatchResultProcessor";
import type { MatchRevenueCalculator } from "./match/MatchRevenueCalculator";

export interface IServiceContainer {
  calendar: CalendarService;
  contract: ContractService;
  dailySimulation: DailySimulationService;
  finance: FinanceService;
  financialHealth: FinancialHealthChecker;
  financialPenalty: FinancialPenaltyService;
  wageCalculator: WageCalculator;
  infrastructure: InfrastructureService;
  marketing: MarketingService;
  match: MatchService;
  cupProgression: CupProgressionManager;
  matchFanSatisfaction: MatchFanSatisfactionProcessor;
  matchFinancials: MatchFinancialsProcessor;
  matchResult: MatchResultProcessor;
  matchRevenue: MatchRevenueCalculator;
  player: PlayerService;
  scouting: ScoutingService;
  season: SeasonService;
  staff: StaffService;
  stats: StatsService;
}
