export const RECOVERY_CONSTANTS = {
  BASE_RATE: 10,
  MAX_FITNESS: 100,
  FITNESS_AFTER_INJURY: 90,
  AGE_YOUNG_THRESHOLD: 25,
  AGE_OLD_THRESHOLD: 32,
  DEFAULT_AGE_IF_UNKNOWN: 25,
  AGE_BONUS_MODIFIER: 0.05,
  AGE_PENALTY_MODIFIER: -0.1,
  RELAPSE_RISK_READINESS: 70,
  STAFF: {
    HIGH_TIER_THRESHOLD: 80,
    HIGH_TIER_BONUS: 0.15,
    MID_TIER_THRESHOLD: 50,
    MID_TIER_BONUS: 0.05,
  },
  INFRA: {
    HIGH_TIER_THRESHOLD: 80,
    HIGH_TIER_BONUS: 0.2,
    MID_TIER_THRESHOLD: 40,
    MID_TIER_BONUS: 0.1,
  },
  MS_PER_YEAR: 31536000000,
} as const;
