import { Position } from "../../domain/enums";

export const FIRST_NAMES = [
  "Miguel",
  "Davi",
  "Arthur",
  "Pedro",
  "Gabriel",
  "Bernardo",
  "Lucas",
  "Matheus",
  "Rafael",
  "Heitor",
  "Enzo",
  "Guilherme",
  "Nicolas",
  "Lorenzo",
  "Gustavo",
  "Felipe",
  "Samuel",
  "João",
  "Daniel",
  "Vitor",
  "Leonardo",
  "Henrique",
  "Theo",
  "Murilo",
  "Eduardo",
  "Caio",
  "Pietro",
  "Vinicius",
  "Benjamin",
  "Isaac",
  "Lucca",
  "Enrico",
  "Bryan",
  "Joaquim",
  "Vicente",
  "Francisco",
  "Antônio",
  "Renan",
  "Bruno",
  "Igor",
  "Luan",
  "Diego",
  "Fábio",
  "Tiago",
  "Marcos",
  "André",
  "Luiz",
  "Alex",
  "Danilo",
  "Ricardo",
  "Jorge",
];

export const LAST_NAMES = [
  "Silva",
  "Santos",
  "Oliveira",
  "Souza",
  "Rodrigues",
  "Ferreira",
  "Alves",
  "Pereira",
  "Lima",
  "Gomes",
  "Costa",
  "Ribeiro",
  "Martins",
  "Carvalho",
  "Almeida",
  "Lopes",
  "Soares",
  "Fernandes",
  "Vieira",
  "Barbosa",
  "Rocha",
  "Dias",
  "Nascimento",
  "Andrade",
  "Moreira",
  "Nunes",
  "Marques",
  "Machado",
  "Mendes",
  "Freitas",
  "Cardoso",
  "Ramos",
  "Gonçalves",
  "Santana",
  "Teixeira",
  "Araújo",
  "Cavalcanti",
  "Barros",
  "Moraes",
  "Castro",
  "Campos",
  "Melo",
  "Batista",
  "Cunha",
  "Pinto",
  "Siqueira",
  "Azevedo",
  "Duarte",
  "Braga",
];

export interface RealPlayer {
  firstName: string;
  lastName: string;
  position: Position;
  age: number;
  overall: number;
  potential: number;
  nationality: string;
}

export interface TeamSeedData {
  name: string;
  short: string;
  primary: string;
  secondary: string;
  rep: number;
  budget: number;
  realPlayers?: RealPlayer[];
}

export const TEAMS_DATA: TeamSeedData[] = [
  {
    name: "Botafogo",
    short: "BOT",
    primary: "#000000",
    secondary: "#FFFFFF",
    rep: 8800,
    budget: 120000000,
    realPlayers: [
      {
        firstName: "Luiz",
        lastName: "Henrique",
        position: Position.FW,
        age: 23,
        overall: 84,
        potential: 88,
        nationality: "BRA",
      },
      {
        firstName: "Thiago",
        lastName: "Almada",
        position: Position.MF,
        age: 23,
        overall: 82,
        potential: 87,
        nationality: "ARG",
      },
      {
        firstName: "Igor",
        lastName: "Jesus",
        position: Position.FW,
        age: 23,
        overall: 80,
        potential: 84,
        nationality: "BRA",
      },
      {
        firstName: "Bastos",
        lastName: "Quissanga",
        position: Position.DF,
        age: 33,
        overall: 79,
        potential: 79,
        nationality: "ANG",
      },
      {
        firstName: "John",
        lastName: "Victor",
        position: Position.GK,
        age: 28,
        overall: 79,
        potential: 81,
        nationality: "BRA",
      },
      {
        firstName: "Marlon",
        lastName: "Freitas",
        position: Position.MF,
        age: 29,
        overall: 78,
        potential: 78,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Palmeiras",
    short: "PAL",
    primary: "#006437",
    secondary: "#FFFFFF",
    rep: 9000,
    budget: 140000000,
    realPlayers: [
      {
        firstName: "Raphael",
        lastName: "Veiga",
        position: Position.MF,
        age: 29,
        overall: 83,
        potential: 83,
        nationality: "BRA",
      },
      {
        firstName: "Estêvão",
        lastName: "Willian",
        position: Position.FW,
        age: 17,
        overall: 82,
        potential: 94,
        nationality: "BRA",
      },
      {
        firstName: "Gustavo",
        lastName: "Gómez",
        position: Position.DF,
        age: 31,
        overall: 82,
        potential: 82,
        nationality: "PAR",
      },
      {
        firstName: "Weverton",
        lastName: "Pereira",
        position: Position.GK,
        age: 36,
        overall: 81,
        potential: 81,
        nationality: "BRA",
      },
      {
        firstName: "Felipe",
        lastName: "Anderson",
        position: Position.MF,
        age: 31,
        overall: 80,
        potential: 80,
        nationality: "BRA",
      },
      {
        firstName: "José",
        lastName: "López",
        position: Position.FW,
        age: 24,
        overall: 79,
        potential: 83,
        nationality: "ARG",
      },
    ],
  },
  {
    name: "Flamengo",
    short: "FLA",
    primary: "#C3281E",
    secondary: "#000000",
    rep: 9100,
    budget: 160000000,
    realPlayers: [
      {
        firstName: "Pedro",
        lastName: "Guilherme",
        position: Position.FW,
        age: 27,
        overall: 85,
        potential: 86,
        nationality: "BRA",
      },
      {
        firstName: "Giorgian",
        lastName: "De Arrascaeta",
        position: Position.MF,
        age: 30,
        overall: 84,
        potential: 84,
        nationality: "URU",
      },
      {
        firstName: "Nicolás",
        lastName: "De La Cruz",
        position: Position.MF,
        age: 27,
        overall: 83,
        potential: 84,
        nationality: "URU",
      },
      {
        firstName: "Gerson",
        lastName: "Santos",
        position: Position.MF,
        age: 27,
        overall: 82,
        potential: 84,
        nationality: "BRA",
      },
      {
        firstName: "Léo",
        lastName: "Ortiz",
        position: Position.DF,
        age: 29,
        overall: 80,
        potential: 82,
        nationality: "BRA",
      },
      {
        firstName: "Agustín",
        lastName: "Rossi",
        position: Position.GK,
        age: 29,
        overall: 79,
        potential: 80,
        nationality: "ARG",
      },
    ],
  },
  {
    name: "Fortaleza",
    short: "FOR",
    primary: "#115E9F",
    secondary: "#C3281E",
    rep: 8200,
    budget: 65000000,
    realPlayers: [
      {
        firstName: "Juan",
        lastName: "Lucero",
        position: Position.FW,
        age: 33,
        overall: 79,
        potential: 79,
        nationality: "ARG",
      },
      {
        firstName: "Hércules",
        lastName: "Pereira",
        position: Position.MF,
        age: 24,
        overall: 78,
        potential: 83,
        nationality: "BRA",
      },
      {
        firstName: "Tomás",
        lastName: "Pochettino",
        position: Position.MF,
        age: 29,
        overall: 77,
        potential: 77,
        nationality: "ARG",
      },
      {
        firstName: "João",
        lastName: "Ricardo",
        position: Position.GK,
        age: 36,
        overall: 78,
        potential: 78,
        nationality: "BRA",
      },
      {
        firstName: "Yago",
        lastName: "Pikachu",
        position: Position.MF,
        age: 32,
        overall: 77,
        potential: 77,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Internacional",
    short: "INT",
    primary: "#E30613",
    secondary: "#FFFFFF",
    rep: 8300,
    budget: 75000000,
    realPlayers: [
      {
        firstName: "Alan",
        lastName: "Patrick",
        position: Position.MF,
        age: 33,
        overall: 81,
        potential: 81,
        nationality: "BRA",
      },
      {
        firstName: "Rafael",
        lastName: "Borré",
        position: Position.FW,
        age: 29,
        overall: 80,
        potential: 80,
        nationality: "COL",
      },
      {
        firstName: "Enner",
        lastName: "Valencia",
        position: Position.FW,
        age: 35,
        overall: 79,
        potential: 79,
        nationality: "ECU",
      },
      {
        firstName: "Sergio",
        lastName: "Rochet",
        position: Position.GK,
        age: 31,
        overall: 79,
        potential: 79,
        nationality: "URU",
      },
      {
        firstName: "Thiago",
        lastName: "Maia",
        position: Position.MF,
        age: 27,
        overall: 77,
        potential: 79,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "São Paulo",
    short: "SAO",
    primary: "#FFFFFF",
    secondary: "#C3281E",
    rep: 8500,
    budget: 90000000,
    realPlayers: [
      {
        firstName: "Lucas",
        lastName: "Moura",
        position: Position.MF,
        age: 32,
        overall: 82,
        potential: 82,
        nationality: "BRA",
      },
      {
        firstName: "Jonathan",
        lastName: "Calleri",
        position: Position.FW,
        age: 31,
        overall: 80,
        potential: 80,
        nationality: "ARG",
      },
      {
        firstName: "Robert",
        lastName: "Arboleda",
        position: Position.DF,
        age: 33,
        overall: 79,
        potential: 79,
        nationality: "ECU",
      },
      {
        firstName: "Rafael",
        lastName: "Pires",
        position: Position.GK,
        age: 35,
        overall: 79,
        potential: 79,
        nationality: "BRA",
      },
      {
        firstName: "Luciano",
        lastName: "Neves",
        position: Position.FW,
        age: 31,
        overall: 78,
        potential: 78,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Corinthians",
    short: "COR",
    primary: "#FFFFFF",
    secondary: "#000000",
    rep: 8400,
    budget: 85000000,
    realPlayers: [
      {
        firstName: "Memphis",
        lastName: "Depay",
        position: Position.FW,
        age: 30,
        overall: 83,
        potential: 83,
        nationality: "NED",
      },
      {
        firstName: "Rodrigo",
        lastName: "Garro",
        position: Position.MF,
        age: 27,
        overall: 81,
        potential: 83,
        nationality: "ARG",
      },
      {
        firstName: "Hugo",
        lastName: "Souza",
        position: Position.GK,
        age: 25,
        overall: 78,
        potential: 82,
        nationality: "BRA",
      },
      {
        firstName: "Yuri",
        lastName: "Alberto",
        position: Position.FW,
        age: 23,
        overall: 78,
        potential: 82,
        nationality: "BRA",
      },
      {
        firstName: "André",
        lastName: "Ramalho",
        position: Position.DF,
        age: 32,
        overall: 77,
        potential: 77,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Bahia",
    short: "BAH",
    primary: "#0032A0",
    secondary: "#E30613",
    rep: 7900,
    budget: 100000000,
    realPlayers: [
      {
        firstName: "Everton",
        lastName: "Ribeiro",
        position: Position.MF,
        age: 35,
        overall: 79,
        potential: 79,
        nationality: "BRA",
      },
      {
        firstName: "Cauly",
        lastName: "Oliveira",
        position: Position.MF,
        age: 29,
        overall: 79,
        potential: 79,
        nationality: "BRA",
      },
      {
        firstName: "Jean",
        lastName: "Lucas",
        position: Position.MF,
        age: 26,
        overall: 77,
        potential: 80,
        nationality: "BRA",
      },
      {
        firstName: "Thaciano",
        lastName: "Mickael",
        position: Position.FW,
        age: 29,
        overall: 77,
        potential: 77,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Cruzeiro",
    short: "CRU",
    primary: "#0047BB",
    secondary: "#FFFFFF",
    rep: 8100,
    budget: 95000000,
    realPlayers: [
      {
        firstName: "Matheus",
        lastName: "Pereira",
        position: Position.MF,
        age: 28,
        overall: 82,
        potential: 83,
        nationality: "BRA",
      },
      {
        firstName: "Cássio",
        lastName: "Ramos",
        position: Position.GK,
        age: 37,
        overall: 79,
        potential: 79,
        nationality: "BRA",
      },
      {
        firstName: "William",
        lastName: "Furtado",
        position: Position.DF,
        age: 29,
        overall: 78,
        potential: 78,
        nationality: "BRA",
      },
      {
        firstName: "Kaio",
        lastName: "Jorge",
        position: Position.FW,
        age: 22,
        overall: 76,
        potential: 81,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Vasco da Gama",
    short: "VAS",
    primary: "#000000",
    secondary: "#FFFFFF",
    rep: 8000,
    budget: 70000000,
    realPlayers: [
      {
        firstName: "Pablo",
        lastName: "Vegetti",
        position: Position.FW,
        age: 36,
        overall: 80,
        potential: 80,
        nationality: "ARG",
      },
      {
        firstName: "Dimitri",
        lastName: "Payet",
        position: Position.MF,
        age: 37,
        overall: 79,
        potential: 79,
        nationality: "FRA",
      },
      {
        firstName: "Philippe",
        lastName: "Coutinho",
        position: Position.MF,
        age: 32,
        overall: 79,
        potential: 79,
        nationality: "BRA",
      },
      {
        firstName: "Léo",
        lastName: "Jardim",
        position: Position.GK,
        age: 29,
        overall: 78,
        potential: 79,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Atlético Mineiro",
    short: "CAM",
    primary: "#000000",
    secondary: "#FFFFFF",
    rep: 8600,
    budget: 110000000,
    realPlayers: [
      {
        firstName: "Givanildo",
        lastName: "Hulk",
        position: Position.FW,
        age: 38,
        overall: 83,
        potential: 83,
        nationality: "BRA",
      },
      {
        firstName: "Paulinho",
        lastName: "Sampaio",
        position: Position.FW,
        age: 24,
        overall: 81,
        potential: 84,
        nationality: "BRA",
      },
      {
        firstName: "Gustavo",
        lastName: "Scarpa",
        position: Position.MF,
        age: 30,
        overall: 80,
        potential: 80,
        nationality: "BRA",
      },
      {
        firstName: "Guilherme",
        lastName: "Arana",
        position: Position.DF,
        age: 27,
        overall: 80,
        potential: 82,
        nationality: "BRA",
      },
      {
        firstName: "Éverson",
        lastName: "Felipe",
        position: Position.GK,
        age: 34,
        overall: 79,
        potential: 79,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Grêmio",
    short: "GRE",
    primary: "#0097D7",
    secondary: "#000000",
    rep: 8000,
    budget: 70000000,
    realPlayers: [
      {
        firstName: "Mathías",
        lastName: "Villasanti",
        position: Position.MF,
        age: 27,
        overall: 79,
        potential: 81,
        nationality: "PAR",
      },
      {
        firstName: "Franco",
        lastName: "Cristaldo",
        position: Position.MF,
        age: 28,
        overall: 78,
        potential: 79,
        nationality: "ARG",
      },
      {
        firstName: "Martin",
        lastName: "Braithwaite",
        position: Position.FW,
        age: 33,
        overall: 78,
        potential: 78,
        nationality: "DEN",
      },
      {
        firstName: "Yeferson",
        lastName: "Soteldo",
        position: Position.FW,
        age: 27,
        overall: 78,
        potential: 79,
        nationality: "VEN",
      },
    ],
  },
  {
    name: "Fluminense",
    short: "FLU",
    primary: "#8A1727",
    secondary: "#075F38",
    rep: 8100,
    budget: 65000000,
    realPlayers: [
      {
        firstName: "Jhon",
        lastName: "Arias",
        position: Position.MF,
        age: 27,
        overall: 81,
        potential: 82,
        nationality: "COL",
      },
      {
        firstName: "Thiago",
        lastName: "Silva",
        position: Position.DF,
        age: 40,
        overall: 80,
        potential: 80,
        nationality: "BRA",
      },
      {
        firstName: "Paulo",
        lastName: "Ganso",
        position: Position.MF,
        age: 35,
        overall: 78,
        potential: 78,
        nationality: "BRA",
      },
      {
        firstName: "Germán",
        lastName: "Cano",
        position: Position.FW,
        age: 36,
        overall: 77,
        potential: 77,
        nationality: "ARG",
      },
      {
        firstName: "Kauã",
        lastName: "Elias",
        position: Position.FW,
        age: 18,
        overall: 74,
        potential: 84,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Red Bull Bragantino",
    short: "RBB",
    primary: "#D71920",
    secondary: "#FFFFFF",
    rep: 7200,
    budget: 80000000,
    realPlayers: [
      {
        firstName: "Cleiton",
        lastName: "Schwengber",
        position: Position.GK,
        age: 27,
        overall: 78,
        potential: 80,
        nationality: "BRA",
      },
      {
        firstName: "Lucas",
        lastName: "Evangelista",
        position: Position.MF,
        age: 29,
        overall: 77,
        potential: 77,
        nationality: "BRA",
      },
      {
        firstName: "Eduardo",
        lastName: "Sasha",
        position: Position.FW,
        age: 32,
        overall: 76,
        potential: 76,
        nationality: "BRA",
      },
      {
        firstName: "Juninho",
        lastName: "Capixaba",
        position: Position.DF,
        age: 27,
        overall: 76,
        potential: 77,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Athletico Paranaense",
    short: "CAP",
    primary: "#E30613",
    secondary: "#000000",
    rep: 7500,
    budget: 70000000,
    realPlayers: [
      {
        firstName: "Agustín",
        lastName: "Canobbio",
        position: Position.FW,
        age: 26,
        overall: 78,
        potential: 80,
        nationality: "URU",
      },
      {
        firstName: "Fernandinho",
        lastName: "Roza",
        position: Position.MF,
        age: 39,
        overall: 78,
        potential: 78,
        nationality: "BRA",
      },
      {
        firstName: "Gonzalo",
        lastName: "Mastriani",
        position: Position.FW,
        age: 31,
        overall: 76,
        potential: 76,
        nationality: "URU",
      },
      {
        firstName: "Kaique",
        lastName: "Rocha",
        position: Position.DF,
        age: 23,
        overall: 75,
        potential: 80,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Santos",
    short: "SAN",
    primary: "#FFFFFF",
    secondary: "#000000",
    rep: 7800,
    budget: 60000000,
    realPlayers: [
      {
        firstName: "João",
        lastName: "Schmidt",
        position: Position.MF,
        age: 31,
        overall: 77,
        potential: 77,
        nationality: "BRA",
      },
      {
        firstName: "Guilherme",
        lastName: "Augusto",
        position: Position.FW,
        age: 29,
        overall: 77,
        potential: 77,
        nationality: "BRA",
      },
      {
        firstName: "Diego",
        lastName: "Pituca",
        position: Position.MF,
        age: 32,
        overall: 76,
        potential: 76,
        nationality: "BRA",
      },
      {
        firstName: "Gil",
        lastName: "Nascimento",
        position: Position.DF,
        age: 37,
        overall: 76,
        potential: 76,
        nationality: "BRA",
      },
      {
        firstName: "Giuliano",
        lastName: "Victor",
        position: Position.MF,
        age: 34,
        overall: 75,
        potential: 75,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Vitória",
    short: "VIT",
    primary: "#E30613",
    secondary: "#000000",
    rep: 6800,
    budget: 35000000,
    realPlayers: [
      {
        firstName: "Lucas",
        lastName: "Arcanjo",
        position: Position.GK,
        age: 26,
        overall: 75,
        potential: 77,
        nationality: "BRA",
      },
      {
        firstName: "Matheus",
        lastName: "Davó",
        position: Position.FW,
        age: 25,
        overall: 73,
        potential: 76,
        nationality: "BRA",
      },
      {
        firstName: "Osvaldo",
        lastName: "Filho",
        position: Position.FW,
        age: 37,
        overall: 73,
        potential: 73,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Juventude",
    short: "JUV",
    primary: "#006437",
    secondary: "#FFFFFF",
    rep: 6600,
    budget: 30000000,
    realPlayers: [
      {
        firstName: "Jadson",
        lastName: "Alves",
        position: Position.MF,
        age: 31,
        overall: 74,
        potential: 74,
        nationality: "BRA",
      },
      {
        firstName: "Nenê",
        lastName: "Carvalho",
        position: Position.MF,
        age: 43,
        overall: 73,
        potential: 73,
        nationality: "BRA",
      },
      {
        firstName: "Erick",
        lastName: "Farias",
        position: Position.FW,
        age: 27,
        overall: 73,
        potential: 74,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Ceará",
    short: "CEA",
    primary: "#000000",
    secondary: "#FFFFFF",
    rep: 6800,
    budget: 35000000,
    realPlayers: [
      {
        firstName: "Erick",
        lastName: "Pulga",
        position: Position.FW,
        age: 24,
        overall: 75,
        potential: 79,
        nationality: "BRA",
      },
      {
        firstName: "Saulo",
        lastName: "Mineiro",
        position: Position.FW,
        age: 27,
        overall: 74,
        potential: 75,
        nationality: "BRA",
      },
      {
        firstName: "Lourenço",
        lastName: "Filho",
        position: Position.MF,
        age: 27,
        overall: 73,
        potential: 75,
        nationality: "BRA",
      },
    ],
  },
  {
    name: "Sport Recife",
    short: "SPT",
    primary: "#E30613",
    secondary: "#000000",
    rep: 6900,
    budget: 38000000,
    realPlayers: [
      {
        firstName: "Lucas",
        lastName: "Lima",
        position: Position.MF,
        age: 34,
        overall: 75,
        potential: 75,
        nationality: "BRA",
      },
      {
        firstName: "Rafael",
        lastName: "Thyere",
        position: Position.DF,
        age: 31,
        overall: 74,
        potential: 74,
        nationality: "BRA",
      },
      {
        firstName: "Fabrício",
        lastName: "Domínguez",
        position: Position.MF,
        age: 26,
        overall: 74,
        potential: 76,
        nationality: "URU",
      },
    ],
  },
];
