export const FIRST_NAMES = [
  "João",
  "Pedro",
  "Tiago",
  "Lucas",
  "Mateus",
  "Gabriel",
  "Rafael",
  "Bruno",
  "André",
  "Miguel",
  "Rui",
  "Nuno",
  "Ricardo",
  "Diogo",
  "Gonçalo",
  "Carlos",
  "Fernando",
  "Manuel",
  "Paulo",
  "António",
  "Jorge",
  "Luís",
  "Sérgio",
];

export const LAST_NAMES = [
  "Silva",
  "Santos",
  "Ferreira",
  "Pereira",
  "Oliveira",
  "Costa",
  "Rodrigues",
  "Martins",
  "Gomes",
  "Lopes",
  "Almeida",
  "Carvalho",
  "Sousa",
  "Ribeiro",
  "Rocha",
  "Monteiro",
  "Teixeira",
  "Mendes",
  "Nunes",
  "Barbosa",
];

export const TEAMS_DATA = [
  {
    name: "Red Eagles",
    short: "RED",
    primary: "#ef4444",
    secondary: "#ffffff",
    rep: 8500,
    budget: 50000000,
  },
  {
    name: "Blue Dragons",
    short: "BLU",
    primary: "#3b82f6",
    secondary: "#ffffff",
    rep: 8200,
    budget: 48000000,
  },
  {
    name: "Green Lions",
    short: "GRN",
    primary: "#22c55e",
    secondary: "#ffffff",
    rep: 7800,
    budget: 45000000,
  },
  {
    name: "White Warriors",
    short: "WHT",
    primary: "#f8fafc",
    secondary: "#0f172a",
    rep: 7200,
    budget: 38000000,
  },
  {
    name: "Black Panthers",
    short: "BLK",
    primary: "#1e293b",
    secondary: "#fbbf24",
    rep: 6800,
    budget: 35000000,
  },
  {
    name: "Golden Suns",
    short: "GLD",
    primary: "#eab308",
    secondary: "#1e293b",
    rep: 6200,
    budget: 30000000,
  },
  {
    name: "Silver Stars",
    short: "SLV",
    primary: "#94a3b8",
    secondary: "#0f172a",
    rep: 5800,
    budget: 25000000,
  },
  {
    name: "Purple Knights",
    short: "PRP",
    primary: "#a855f7",
    secondary: "#ffffff",
    rep: 5400,
    budget: 22000000,
  },
  {
    name: "Orange Tigers",
    short: "ORG",
    primary: "#f97316",
    secondary: "#ffffff",
    rep: 5000,
    budget: 20000000,
  },
  {
    name: "Cyan Dolphins",
    short: "CYN",
    primary: "#06b6d4",
    secondary: "#ffffff",
    rep: 4600,
    budget: 18000000,
  },
  {
    name: "Pink Flamingos",
    short: "PNK",
    primary: "#ec4899",
    secondary: "#ffffff",
    rep: 4200,
    budget: 15000000,
  },
  {
    name: "Brown Bears",
    short: "BRN",
    primary: "#92400e",
    secondary: "#fef3c7",
    rep: 3800,
    budget: 12000000,
  },
];
